### ISSUE TITLE
View post page

### ISSUE THREAD

**Issue by tatupesonen** [vanilla-react/core#35]
View post page needs the following functionality:

- [x] Add kudos to a post
- [x] View the post
- [x] Follow the API post routing convention
- [x] Redirect from create post to the created post
- [x] Add container for feedback
- [x] Update seeds to have 2 snippets

**Comment by donnyroufs** [comment]
![image](https://user-images.githubusercontent.com/48981403/115399953-02b80b80-a1e9-11eb-8fcd-2c8f6c83d80f.png)

**Comment by donnyroufs** [comment]
![image](https://user-images.githubusercontent.com/48981403/115400005-106d9100-a1e9-11eb-943b-e56ff1d235e9.png)
